### ISSUE TITLE
i've been waiting 3 years for an update, you forgot about it didnt you

### ISSUE THREAD

**Issue by Mazedotexe** [Techcrafter/RUMBLO#1]
:(

**Comment by Techcrafter** [comment]
Sorry for the late response!
It's not that I forgot about it, but I simply do not plan on developing any further updates for this game. It got a very reasonable amount of downloads and I really appreciate that, but I'm honestly no longer into game development. It just involves so many aspects besides coding that I'm not really that good at (graphic and sound design just to name two).
Thank you very much though for playing RUMBLO all these year!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mazedotexe ***@***.***>
Sent: Wednesday, December 27, 2023 7:17:16 AM
To: Techcrafter/RUMBLO ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Techcrafter/RUMBLO] i've been waiting 3 years for an update, you forgot about it didnt you (Issue #1)


:(

**Comment by Techcrafter** [comment]
Sorry for the late response!
It's not that I forgot about it, but I simply do not plan on developing any further updates for this game. It got a very reasonable amount of downloads and I really appreciate that, but I'm honestly no longer into game development. It just involves so many aspects besides coding that I'm not really that good at (graphic and sound design just to name two).
Thank you very much though for playing RUMBLO all these year!
